# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89e0383991639304a0e99507b60d5cf356efa896057af5c2879cd02965f7696e0503208d451b7bb0842df585e1ded7e537a5f2592218d83e2a7ca3e8c877db98

test:
  secret_key_base: ec45717984124358a1f49f79b14b53d8c94c739d4082146b8d4ca56f1eb380d7577e0b4816a0b56ee372fe174dfbff35823781bd3fe6d182ab93d3c68efe9e4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
